### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-JazminloRI#1]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-JazminloRI/files/8580579/Infografia.pdf)

**Comment by bg55-a** [comment]
Calificación: 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
